"use client";

import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import { LazyVideo } from "@/components/LazyVideo";

const tournamentStats = [
  { label: "Regional Tournament", teams: "50 teams", athletes: "750 athletes", revenue: "$1,839/month approx." },
  { label: "National Tournament", teams: "500 teams", athletes: "7,500 athletes", revenue: "$18,357/month approx." },
];

export function PartnerTournament() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <section className="relative py-20 md:py-28 overflow-hidden" ref={ref}>
      <div className="absolute inset-0 bg-gradient-to-b from-surface via-surface-light/30 to-surface" />

      <div className="relative mx-auto max-w-7xl px-5 md:px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* Left: Content */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.6 }}
          >
            <span className="text-xs font-semibold uppercase tracking-widest text-primary-light mb-4 block">
              Tournament & Institutional Partners
            </span>
            <h2 className="font-display text-2xl md:text-4xl font-black mb-4 md:mb-6 uppercase tracking-tight">
              One Tournament.{" "}
              <span className="gradient-text">Hundreds of Partners.</span>
            </h2>
            <p className="text-text-secondary text-sm md:text-base leading-relaxed mb-6">
              Tournaments create awareness at scale. When 500 teams hear about
              Athletic Mindset in one weekend, coaches sign up, athletes
              subscribe, and the flywheel spins itself.
            </p>
            <p className="text-text-secondary text-sm md:text-base leading-relaxed mb-8">
              Institutional partners — tournaments, governing bodies, leagues —
              earn a <span className="text-text-primary font-medium">5% override</span> on
              all revenue generated by coaches they refer. No cap. No sponsorship
              fees. Pure performance.
            </p>

            {/* Stats */}
            <div className="space-y-4">
              {tournamentStats.map((stat, index) => (
                <motion.div
                  key={stat.label}
                  initial={{ opacity: 0, y: 20 }}
                  animate={isInView ? { opacity: 1, y: 0 } : {}}
                  transition={{ duration: 0.5, delay: 0.3 + index * 0.1 }}
                  className="rounded-xl border border-border/50 bg-surface-card/50 p-4 flex items-center justify-between"
                >
                  <div>
                    <p className="text-sm font-semibold text-text-primary">
                      {stat.label}
                    </p>
                    <p className="text-xs text-text-muted">
                      {stat.teams} · {stat.athletes}
                    </p>
                  </div>
                  <p className="text-lg md:text-xl font-bold text-primary-light">
                    {stat.revenue}
                  </p>
                </motion.div>
              ))}
            </div>
          </motion.div>

          {/* Right: Video/Visual */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="relative"
          >
            <div className="relative rounded-2xl overflow-hidden aspect-[4/3]">
              <LazyVideo
                src="/videos/athlete-3.mp4"
                className="w-full h-full object-cover"
              />
              <div className="absolute inset-0 bg-surface/40" />
              <div className="absolute inset-0 bg-gradient-to-t from-surface/80 to-transparent" />

              {/* Overlay content */}
              <div className="absolute bottom-0 left-0 right-0 p-6">
                <p className="text-xs font-semibold uppercase tracking-widest text-primary-light mb-2">
                  The Flywheel
                </p>
                <p className="text-sm text-text-secondary leading-relaxed">
                  One tournament partnership → hundreds of coaches → thousands of
                  athletes → years of recurring revenue.
                </p>
              </div>
            </div>
            {/* Glow */}
            <div className="absolute inset-0 -z-10 rounded-2xl bg-primary/5 blur-3xl scale-110" />
          </motion.div>
        </div>
      </div>
    </section>
  );
}
